# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-07 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productproperty',
            options={'verbose_name': 'Product property', 'verbose_name_plural': 'Product properties'},
        ),
    ]
